CREATE TABLE `by_sample` (
  `source` TEXT,
  `study` TEXT,
  `datatype` TEXT,
  `country` TEXT,
  `year` TEXT,
  `site` TEXT,
  `latitude` REAL,
  `longitude` REAL,
  `ID` TEXT,
  `exclude` TEXT DEFAULT 'no',
  `locus` TEXT,
  `chromosome` TEXT,
  `position` INT,
  `ref_allele` TEXT,
  `alt_allele` TEXT,
  `ref` INTEGER,
  `mixed` INTEGER,
  `nonref` INTEGER,
  `read_count_ref` INT,
  `read_count_alt` INT
) ;
